###
GET http://localhost:8080/jobs/pms/all?pageNum=0&pageSize=5
Accept: application/json
Cache-Control: no-cache

###
GET http://localhost:8080/jobs/pms/all
Accept: application/json
Cache-Control: no-cache

###